"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# ----------------------------
# Base directory
# ----------------------------
BASE_DIR = Path(__file__).resolve().parent.parent


# ----------------------------
# SECURITY CONFIGURATION
# ----------------------------

# Keep the secret key secret in production!
SECRET_KEY = 'django-insecure-#=8#y3bmorxat-*a*t8p#px%=8q-u8n5gx_%7n&l399@kg^dp6'

# Disable debug mode for production
DEBUG = False

# Allow all hosts temporarily (adjust in production)
ALLOWED_HOSTS = ['*']

# --- Enforce HTTPS and Secure Redirects ---
# Redirect all HTTP requests to HTTPS
SECURE_SSL_REDIRECT = True

# Use HTTP Strict Transport Security (HSTS)
# Tells browsers to always use HTTPS for this domain for 1 year (31536000 seconds)
SECURE_HSTS_SECONDS = 31536000
# Apply HSTS policy to all subdomains
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# Enable HSTS preload for browser preload lists
SECURE_HSTS_PRELOAD = True

# --- Secure Cookies ---
# Ensure session cookies are only sent via HTTPS
SESSION_COOKIE_SECURE = True
# Ensure CSRF cookies are only sent via HTTPS
CSRF_COOKIE_SECURE = True

# --- Secure Headers ---
# Prevent browsers from guessing file content types
SECURE_CONTENT_TYPE_NOSNIFF = True
# Enable browser’s XSS filter to help prevent XSS attacks
SECURE_BROWSER_XSS_FILTER = True
# Prevent the site from being rendered inside an iframe (clickjacking protection)
X_FRAME_OPTIONS = 'DENY'


# ----------------------------
# Application definition
# ----------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bookshelf',
    'relationship_app',
    'users',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'LibraryProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LibraryProject.wsgi.application'


# ----------------------------
# Database
# ----------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Custom user model
AUTH_USER_MODEL = "users.CustomUser"


# ----------------------------
# Password validation
# ----------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# ----------------------------
# Internationalization
# ----------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# ----------------------------
# Static files
# ----------------------------
STATIC_URL = 'static/'


# ----------------------------
# Default primary key field type
# ----------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
